// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package common

import "strconv"

/// Schema types for routing and streaming
type SchemaType byte

const (
	SchemaTypeUNKNOWN   SchemaType = 0
	SchemaTypeEVENT     SchemaType = 1
	SchemaTypeLOG       SchemaType = 2
	SchemaTypeMETRIC    SchemaType = 3
	SchemaTypeINVENTORY SchemaType = 4
)

var EnumNamesSchemaType = map[SchemaType]string{
	SchemaTypeUNKNOWN:   "UNKNOWN",
	SchemaTypeEVENT:     "EVENT",
	SchemaTypeLOG:       "LOG",
	SchemaTypeMETRIC:    "METRIC",
	SchemaTypeINVENTORY: "INVENTORY",
}

var EnumValuesSchemaType = map[string]SchemaType{
	"UNKNOWN":   SchemaTypeUNKNOWN,
	"EVENT":     SchemaTypeEVENT,
	"LOG":       SchemaTypeLOG,
	"METRIC":    SchemaTypeMETRIC,
	"INVENTORY": SchemaTypeINVENTORY,
}

func (v SchemaType) String() string {
	if s, ok := EnumNamesSchemaType[v]; ok {
		return s
	}
	return "SchemaType(" + strconv.FormatInt(int64(v), 10) + ")"
}
