// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package event

import "strconv"

/// Event types for different processing paths
type EventType uint32

const (
	EventTypeUNKNOWN  EventType = 0
	EventTypeTRACK    EventType = 1
	EventTypeIDENTIFY EventType = 2
	EventTypeGROUP    EventType = 3
	EventTypeALIAS    EventType = 4
	EventTypeENRICH   EventType = 5
)

var EnumNamesEventType = map[EventType]string{
	EventTypeUNKNOWN:  "UNKNOWN",
	EventTypeTRACK:    "TRACK",
	EventTypeIDENTIFY: "IDENTIFY",
	EventTypeGROUP:    "GROUP",
	EventTypeALIAS:    "ALIAS",
	EventTypeENRICH:   "ENRICH",
}

var EnumValuesEventType = map[string]EventType{
	"UNKNOWN":  EventTypeUNKNOWN,
	"TRACK":    EventTypeTRACK,
	"IDENTIFY": EventTypeIDENTIFY,
	"GROUP":    EventTypeGROUP,
	"ALIAS":    EventTypeALIAS,
	"ENRICH":   EventTypeENRICH,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
