// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package event

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Event data container (goes in UnifiedBatch.data)
type EventData struct {
	_tab flatbuffers.Table
}

func GetRootAsEventData(buf []byte, offset flatbuffers.UOffsetT) *EventData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EventData{}
	x.Init(buf, n+offset)
	return x
}

func FinishEventDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEventData(buf []byte, offset flatbuffers.UOffsetT) *EventData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EventData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEventDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EventData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EventData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EventData) Events(obj *Event, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EventData) EventsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EventDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EventDataAddEvents(builder *flatbuffers.Builder, events flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(events), 0)
}
func EventDataStartEventsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EventDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
