// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package log

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogData struct {
	_tab flatbuffers.Table
}

func GetRootAsLogData(buf []byte, offset flatbuffers.UOffsetT) *LogData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogData{}
	x.Init(buf, n+offset)
	return x
}

func FinishLogDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLogData(buf []byte, offset flatbuffers.UOffsetT) *LogData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLogDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LogData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogData) Logs(obj *LogEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *LogData) LogsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LogDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LogDataAddLogs(builder *flatbuffers.Builder, logs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(logs), 0)
}
func LogDataStartLogsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LogDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
