// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package log

import "strconv"

/// Log-specific event types
/// Optimized to uint8 since we only have a few types (was uint32)
/// Used for routing and processing pipeline decisions
type LogEventType byte

const (
	LogEventTypeUNKNOWN LogEventType = 0
	LogEventTypeLOG     LogEventType = 1
	LogEventTypeENRICH  LogEventType = 2
)

var EnumNamesLogEventType = map[LogEventType]string{
	LogEventTypeUNKNOWN: "UNKNOWN",
	LogEventTypeLOG:     "LOG",
	LogEventTypeENRICH:  "ENRICH",
}

var EnumValuesLogEventType = map[string]LogEventType{
	"UNKNOWN": LogEventTypeUNKNOWN,
	"LOG":     LogEventTypeLOG,
	"ENRICH":  LogEventTypeENRICH,
}

func (v LogEventType) String() string {
	if s, ok := EnumNamesLogEventType[v]; ok {
		return s
	}
	return "LogEventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
