// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package log

import "strconv"

/// Log-specific event types
type LogEventType uint32

const (
	LogEventTypeUNKNOWN LogEventType = 0
	LogEventTypeCOLLECT LogEventType = 1
	LogEventTypeENRICH  LogEventType = 2
	LogEventTypeAUTH    LogEventType = 3
)

var EnumNamesLogEventType = map[LogEventType]string{
	LogEventTypeUNKNOWN: "UNKNOWN",
	LogEventTypeCOLLECT: "COLLECT",
	LogEventTypeENRICH:  "ENRICH",
	LogEventTypeAUTH:    "AUTH",
}

var EnumValuesLogEventType = map[string]LogEventType{
	"UNKNOWN": LogEventTypeUNKNOWN,
	"COLLECT": LogEventTypeCOLLECT,
	"ENRICH":  LogEventTypeENRICH,
	"AUTH":    LogEventTypeAUTH,
}

func (v LogEventType) String() string {
	if s, ok := EnumNamesLogEventType[v]; ok {
		return s
	}
	return "LogEventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
