// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package log

import "strconv"

/// Log severity levels (standard)
type LogLevel byte

const (
	LogLevelEMERGENCY LogLevel = 0
	LogLevelALERT     LogLevel = 1
	LogLevelCRITICAL  LogLevel = 2
	LogLevelERROR     LogLevel = 3
	LogLevelWARNING   LogLevel = 4
	LogLevelNOTICE    LogLevel = 5
	LogLevelINFO      LogLevel = 6
	LogLevelDEBUG     LogLevel = 7
	LogLevelTRACE     LogLevel = 8
)

var EnumNamesLogLevel = map[LogLevel]string{
	LogLevelEMERGENCY: "EMERGENCY",
	LogLevelALERT:     "ALERT",
	LogLevelCRITICAL:  "CRITICAL",
	LogLevelERROR:     "ERROR",
	LogLevelWARNING:   "WARNING",
	LogLevelNOTICE:    "NOTICE",
	LogLevelINFO:      "INFO",
	LogLevelDEBUG:     "DEBUG",
	LogLevelTRACE:     "TRACE",
}

var EnumValuesLogLevel = map[string]LogLevel{
	"EMERGENCY": LogLevelEMERGENCY,
	"ALERT":     LogLevelALERT,
	"CRITICAL":  LogLevelCRITICAL,
	"ERROR":     LogLevelERROR,
	"WARNING":   LogLevelWARNING,
	"NOTICE":    LogLevelNOTICE,
	"INFO":      LogLevelINFO,
	"DEBUG":     LogLevelDEBUG,
	"TRACE":     LogLevelTRACE,
}

func (v LogLevel) String() string {
	if s, ok := EnumNamesLogLevel[v]; ok {
		return s
	}
	return "LogLevel(" + strconv.FormatInt(int64(v), 10) + ")"
}
